/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author pedro
 */
public class EditarPedido extends javax.swing.JFrame {

    /**
     * Creates new form EditarPedido
     */
    public EditarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaTextoIngredientesProduto = new javax.swing.JTextField();
        BotaoIncluir = new javax.swing.JButton();
        CelClient = new javax.swing.JLabel();
        QuantidadeProduto = new javax.swing.JLabel();
        BotaoIncluir1 = new javax.swing.JButton();
        Produto = new javax.swing.JLabel();
        BotaoIncluir2 = new javax.swing.JButton();
        CaixaTextoCelClient = new javax.swing.JTextField();
        DescricaoProduto = new javax.swing.JLabel();
        CaixaTextoQuantidadeProduto = new javax.swing.JTextField();
        CaixaTextoDescricaoProduto = new javax.swing.JTextField();
        CaixaTextoProdutoAlterar = new javax.swing.JTextField();
        ProdutoAlterar = new javax.swing.JLabel();
        FundoCadastroFuncionario = new javax.swing.JLabel();
        FundoPrincipal = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        BotaoCadastroFuncionario = new javax.swing.JMenuItem();
        BotaoCadastroCliente = new javax.swing.JMenuItem();
        ProdutosBebidas = new javax.swing.JMenuItem();
        ProdutoLanches = new javax.swing.JMenuItem();
        MenuPedidos = new javax.swing.JMenu();
        IncluirPedido = new javax.swing.JMenuItem();
        EditarPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CaixaTextoIngredientesProduto.setBackground(new java.awt.Color(255, 255, 255));
        CaixaTextoIngredientesProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaTextoIngredientesProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaTextoIngredientesProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 370, -1));

        BotaoIncluir.setBackground(new java.awt.Color(204, 255, 255));
        BotaoIncluir.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoIncluir.setForeground(new java.awt.Color(0, 0, 0));
        BotaoIncluir.setText("Atualizar Item");
        BotaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 450, -1, -1));

        CelClient.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        CelClient.setForeground(new java.awt.Color(255, 255, 255));
        CelClient.setText("Id Cliente:");
        getContentPane().add(CelClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, -1, -1));

        QuantidadeProduto.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        QuantidadeProduto.setForeground(new java.awt.Color(255, 255, 255));
        QuantidadeProduto.setText("Quantidade:");
        getContentPane().add(QuantidadeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, -1, -1));

        BotaoIncluir1.setBackground(new java.awt.Color(204, 255, 255));
        BotaoIncluir1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoIncluir1.setForeground(new java.awt.Color(0, 0, 0));
        BotaoIncluir1.setText("Visualizar Pedido");
        BotaoIncluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoIncluir1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoIncluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 490, -1, -1));

        Produto.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Produto.setForeground(new java.awt.Color(255, 255, 255));
        Produto.setText("Produto:");
        getContentPane().add(Produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, -1, -1));

        BotaoIncluir2.setBackground(new java.awt.Color(204, 255, 255));
        BotaoIncluir2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoIncluir2.setForeground(new java.awt.Color(0, 0, 0));
        BotaoIncluir2.setText("Fechar Pedido");
        BotaoIncluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoIncluir2ActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoIncluir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 530, -1, -1));

        CaixaTextoCelClient.setBackground(new java.awt.Color(255, 255, 255));
        CaixaTextoCelClient.setText("Celuar do Cliente");
        CaixaTextoCelClient.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        CaixaTextoCelClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaTextoCelClientActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaTextoCelClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 370, -1));

        DescricaoProduto.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        DescricaoProduto.setForeground(new java.awt.Color(255, 255, 255));
        DescricaoProduto.setText("Observações:");
        getContentPane().add(DescricaoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, -1, -1));

        CaixaTextoQuantidadeProduto.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(CaixaTextoQuantidadeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 370, 370, -1));

        CaixaTextoDescricaoProduto.setBackground(new java.awt.Color(255, 255, 255));
        CaixaTextoDescricaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaTextoDescricaoProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaTextoDescricaoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, 370, -1));

        CaixaTextoProdutoAlterar.setBackground(new java.awt.Color(255, 255, 255));
        CaixaTextoProdutoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaTextoProdutoAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaTextoProdutoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 370, -1));

        ProdutoAlterar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        ProdutoAlterar.setForeground(new java.awt.Color(255, 255, 255));
        ProdutoAlterar.setText("Novo Produto:");
        getContentPane().add(ProdutoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, -1, -1));

        FundoCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/FundoDosCadastros.png"))); // NOI18N
        FundoCadastroFuncionario.setText("jLabel1");
        getContentPane().add(FundoCadastroFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        FundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/MenuPrincipal.png"))); // NOI18N
        getContentPane().add(FundoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MenuCadastro.setText("Cadastro");

        BotaoCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/Icons/Funcionário.png"))); // NOI18N
        BotaoCadastroFuncionario.setText("Funcionário");
        BotaoCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroFuncionarioActionPerformed(evt);
            }
        });
        MenuCadastro.add(BotaoCadastroFuncionario);

        BotaoCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/Icons/Cliente.png"))); // NOI18N
        BotaoCadastroCliente.setText("Cliente");
        BotaoCadastroCliente.setMinimumSize(new java.awt.Dimension(144, 42));
        BotaoCadastroCliente.setPreferredSize(new java.awt.Dimension(144, 42));
        BotaoCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroClienteActionPerformed(evt);
            }
        });
        MenuCadastro.add(BotaoCadastroCliente);

        ProdutosBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/Icons/Refri.png"))); // NOI18N
        ProdutosBebidas.setText("Bebidas");
        MenuCadastro.add(ProdutosBebidas);

        ProdutoLanches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/Icons/Hamburger.png"))); // NOI18N
        ProdutoLanches.setText("Lanches");
        ProdutoLanches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoLanchesActionPerformed(evt);
            }
        });
        MenuCadastro.add(ProdutoLanches);

        BarraMenu.add(MenuCadastro);

        MenuPedidos.setText("Pedido");

        IncluirPedido.setText("Incluir Pedido");
        IncluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncluirPedidoActionPerformed(evt);
            }
        });
        MenuPedidos.add(IncluirPedido);

        EditarPedido.setText("Editar Pedido");
        EditarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPedidoActionPerformed(evt);
            }
        });
        MenuPedidos.add(EditarPedido);

        BarraMenu.add(MenuPedidos);

        setJMenuBar(BarraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CaixaTextoIngredientesProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaTextoIngredientesProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaTextoIngredientesProdutoActionPerformed

    private void BotaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoIncluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoIncluirActionPerformed

    private void BotaoIncluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoIncluir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoIncluir1ActionPerformed

    private void BotaoCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastroFuncionarioActionPerformed

    private void BotaoCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastroClienteActionPerformed

    private void ProdutoLanchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoLanchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutoLanchesActionPerformed

    private void IncluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncluirPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncluirPedidoActionPerformed

    private void EditarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarPedidoActionPerformed

    private void BotaoIncluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoIncluir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoIncluir2ActionPerformed

    private void CaixaTextoCelClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaTextoCelClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaTextoCelClientActionPerformed

    private void CaixaTextoDescricaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaTextoDescricaoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaTextoDescricaoProdutoActionPerformed

    private void CaixaTextoProdutoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaTextoProdutoAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaTextoProdutoAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem BotaoCadastroCliente;
    private javax.swing.JMenuItem BotaoCadastroFuncionario;
    private javax.swing.JButton BotaoIncluir;
    private javax.swing.JButton BotaoIncluir1;
    private javax.swing.JButton BotaoIncluir2;
    private javax.swing.JTextField CaixaTextoCelClient;
    private javax.swing.JTextField CaixaTextoDescricaoProduto;
    private javax.swing.JTextField CaixaTextoIngredientesProduto;
    private javax.swing.JTextField CaixaTextoProdutoAlterar;
    private javax.swing.JTextField CaixaTextoQuantidadeProduto;
    private javax.swing.JLabel CelClient;
    private javax.swing.JLabel DescricaoProduto;
    private javax.swing.JMenuItem EditarPedido;
    private javax.swing.JLabel FundoCadastroFuncionario;
    private javax.swing.JLabel FundoPrincipal;
    private javax.swing.JMenuItem IncluirPedido;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuPedidos;
    private javax.swing.JLabel Produto;
    private javax.swing.JLabel ProdutoAlterar;
    private javax.swing.JMenuItem ProdutoLanches;
    private javax.swing.JMenuItem ProdutosBebidas;
    private javax.swing.JLabel QuantidadeProduto;
    // End of variables declaration//GEN-END:variables
}
