/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoginController;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author pedro
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form views
     */
    public Login() {
        initComponents();
        controller = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoEntrar = new javax.swing.JButton();
        TextUsuario = new javax.swing.JTextField();
        TextSenha = new javax.swing.JPasswordField();
        TituloUsuario = new javax.swing.JLabel();
        TituloSenha = new javax.swing.JLabel();
        TituloLogin = new javax.swing.JLabel();
        CaixaLogin = new javax.swing.JLabel();
        ImagemInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoEntrar.setBackground(new java.awt.Color(204, 255, 255));
        BotaoEntrar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BotaoEntrar.setForeground(new java.awt.Color(0, 0, 0));
        BotaoEntrar.setText("ENTRAR");
        BotaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 710, -1, -1));

        TextUsuario.setBackground(new java.awt.Color(153, 153, 255));
        TextUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 160, -1));

        TextSenha.setBackground(new java.awt.Color(153, 153, 255));
        TextSenha.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        TextSenha.setForeground(new java.awt.Color(0, 0, 0));
        TextSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, 160, -1));

        TituloUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TituloUsuario.setText("Usuário");
        getContentPane().add(TituloUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, -1, -1));

        TituloSenha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TituloSenha.setText("Senha");
        getContentPane().add(TituloSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 620, -1, -1));

        TituloLogin.setFont(new java.awt.Font("Ramabhadra", 0, 36)); // NOI18N
        TituloLogin.setText("Login");
        getContentPane().add(TituloLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        CaixaLogin.setForeground(new java.awt.Color(255, 255, 255));
        CaixaLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CaixaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/RetanguloLogin.png"))); // NOI18N
        getContentPane().add(CaixaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        ImagemInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/LoginMagro.png"))); // NOI18N
        getContentPane().add(ImagemInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void TextSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenhaActionPerformed

    private void BotaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEntrarActionPerformed
        // executar quando clicar no botão entrar:
        this.controller.FizLogin();

        
    }//GEN-LAST:event_BotaoEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoEntrar;
    private javax.swing.JLabel CaixaLogin;
    private javax.swing.JLabel ImagemInicial;
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JLabel TituloLogin;
    private javax.swing.JLabel TituloSenha;
    private javax.swing.JLabel TituloUsuario;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    public JPasswordField getTextSenha() {
        return TextSenha;
    }

    public void setTextSenha(JPasswordField TextSenha) {
        this.TextSenha = TextSenha;
    }

    public JTextField getTextUsuario() {
        return TextUsuario;
    }

    public void setTextUsuario(JTextField TextUsuario) {
        this.TextUsuario = TextUsuario;
    }
    
    
}
