/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author pedro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagemFundo = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        BotaoCadastroFuncionario = new javax.swing.JMenuItem();
        BotaoCadastroCliente = new javax.swing.JMenuItem();
        ProdutosBebidas = new javax.swing.JMenuItem();
        ProdutoLanches = new javax.swing.JMenuItem();
        MenuPedidos = new javax.swing.JMenu();
        IncluirPedido = new javax.swing.JMenuItem();
        EditarPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/MenuPrincipal.png"))); // NOI18N

        MenuCadastro.setText("Cadastro");

        BotaoCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/Icons/Funcionário.png"))); // NOI18N
        BotaoCadastroFuncionario.setText("Funcionário");
        BotaoCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroFuncionarioActionPerformed(evt);
            }
        });
        MenuCadastro.add(BotaoCadastroFuncionario);

        BotaoCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/Icons/Cliente.png"))); // NOI18N
        BotaoCadastroCliente.setText("Cliente");
        BotaoCadastroCliente.setMinimumSize(new java.awt.Dimension(144, 42));
        BotaoCadastroCliente.setPreferredSize(new java.awt.Dimension(144, 42));
        BotaoCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroClienteActionPerformed(evt);
            }
        });
        MenuCadastro.add(BotaoCadastroCliente);

        ProdutosBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/Icons/Refri.png"))); // NOI18N
        ProdutosBebidas.setText("Bebidas");
        MenuCadastro.add(ProdutosBebidas);

        ProdutoLanches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImagens/Icons/Hamburger.png"))); // NOI18N
        ProdutoLanches.setText("Lanches");
        ProdutoLanches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoLanchesActionPerformed(evt);
            }
        });
        MenuCadastro.add(ProdutoLanches);

        BarraMenu.add(MenuCadastro);

        MenuPedidos.setText("Pedido");

        IncluirPedido.setText("Incluir Pedido");
        IncluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncluirPedidoActionPerformed(evt);
            }
        });
        MenuPedidos.add(IncluirPedido);

        EditarPedido.setText("Editar Pedido");
        EditarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPedidoActionPerformed(evt);
            }
        });
        MenuPedidos.add(EditarPedido);

        BarraMenu.add(MenuPedidos);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemFundo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastroFuncionarioActionPerformed

    private void BotaoCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastroClienteActionPerformed

    private void ProdutoLanchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoLanchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutoLanchesActionPerformed

    private void IncluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncluirPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncluirPedidoActionPerformed

    private void EditarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem BotaoCadastroCliente;
    private javax.swing.JMenuItem BotaoCadastroFuncionario;
    private javax.swing.JMenuItem EditarPedido;
    private javax.swing.JLabel ImagemFundo;
    private javax.swing.JMenuItem IncluirPedido;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuPedidos;
    private javax.swing.JMenuItem ProdutoLanches;
    private javax.swing.JMenuItem ProdutosBebidas;
    // End of variables declaration//GEN-END:variables
}
